name: Test

on: [push]

jobs:
  test:
    # где запускаем
    runs-on: ubuntu-latest

    # что делаем
    steps:
      # выкачиваем репозиторий
      - uses: actions/checkout@v3

      # настраиваем java
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      # запускаем тесты
      - run: chmod +x ./gradlew
      - run: ./gradlew clean test